### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by janb89** [janb89/groupwork2#6]
- Increasing domain knowledge
- Getting familiar with data
- Looking for outliers
- Visualize 
- (data cleaning)

**Comment by tamap94** [comment]
EDA hypotheses: 

1. The flights in the afternoon (after 12 pm) are usually more delayed than the early flights 
2. If the flight is already delayed in the morning, it will even delay more in the afternoon (there is as positive correlation) 
3. The flights are more often delayed at a certain time of the year (vacation time, seasonal bad weather) 
4. Optional: there is a correlation between weather and the delay of airplanes 
5. The delays cluster at certain airports (because they are worse organised than others)
